/* Sample Category */
INSERT INTO BOARD_CATEGORY (CATEGORY_ID, CATEGORY_NAME, CATEGORY_CLASS1, CATEGORY_CLASS2, CATEGORY_DESCRIPTION, CATEGORY_ORDER)
VALUES(SEQ_BOARD_CATEGORY_ID.NEXTVAL, '게시판', 1, 10, '게시판', 100);

INSERT INTO BOARD_CATEGORY (CATEGORY_ID, CATEGORY_NAME, CATEGORY_CLASS1, CATEGORY_CLASS2, CATEGORY_DESCRIPTION, CATEGORY_ORDER)
VALUES(SEQ_BOARD_CATEGORY_ID.NEXTVAL, '자료실', 1, 10, '자료실', 200);

INSERT INTO BOARD_CATEGORY (CATEGORY_ID, CATEGORY_NAME, CATEGORY_CLASS1, CATEGORY_CLASS2, CATEGORY_DESCRIPTION, CATEGORY_ORDER)
VALUES(SEQ_BOARD_CATEGORY_ID.NEXTVAL, '겔러리', 1, 10, '겔러리', 300);

COMMIT;

